/**
 * ╔═══════════════════════════════════════════════════════════════════════════════╗
 * ║                                                                             ║
 * ║               🧠  A I  C H A T  —  COMPLETE AI SYSTEM                       ║
 * ║                                                                             ║
 * ║   A single-file, advanced AI that can:                                      ║
 * ║     ✦ Chat intelligently with users                                         ║
 * ║     ✦ Write code in 24 languages (like a senior developer)                 ║
 * ║     ✦ Analyze & describe photos/images (vision AI)                          ║
 * ║     ✦ Review and fix code                                                   ║
 * ║     ✦ Search conversations with fuzzy/regex matching                        ║
 * ║     ✦ Track analytics (tokens, cost, latency, tools)                        ║
 * ║     ✦ Export conversations (Markdown, JSON, Text)                           ║
 * ║     ✦ Branch conversations & manage context windows                         ║
 * ║     ✦ Save and restore sessions                                             ║
 * ║                                                                             ║
 * ║   Built from these sections (all in one file):                              ║
 * ║                                                                             ║
 * ║     §1  TYPES              — Every data shape the AI uses                   ║
 * ║     §2  SEARCH ENGINE      — Find any message instantly                     ║
 * ║     §3  ANALYTICS ENGINE   — Token, cost & tool tracking                    ║
 * ║     §4  EXPORT ENGINE      — Markdown / JSON / Text output                  ║
 * ║     §5  CODE WRITER        — Generate, review & fix code                    ║
 * ║     §6  IMAGE ANALYZER     — Describe & understand photos                   ║
 * ║     §7  AI BRAIN           — Core intelligence (Claude API)                 ║
 * ║     §8  ADVANCED CHAT      — Main class tying it all together               ║
 * ║                                                                             ║
 * ╚═══════════════════════════════════════════════════════════════════════════════╝
 */

// ╔═══════════════════════════════════════════════════════════════════════════════╗
// ║                                                                             ║
// ║  §1  TYPES — Every data shape the AI uses                                   ║
// ║                                                                             ║
// ║  WHY THIS WAS MADE:                                                         ║
// ║  TypeScript types catch bugs at compile time and serve as documentation.     ║
// ║  Every message, conversation, search query, analytics result, code request,  ║
// ║  and image analysis has a precise type defined here.                         ║
// ║                                                                             ║
// ╚═══════════════════════════════════════════════════════════════════════════════╝

// ── Message Primitives ───────────────────────────────────────────────────────

export type ChatMessageId = string
export type BranchId = string
export type ChatRole = 'user' | 'assistant' | 'system' | 'tool'
export type ContentBlockType = 'text' | 'tool_use' | 'tool_result' | 'image' | 'code'

/** A single content block inside a message. */
export interface ContentBlock {
  type: ContentBlockType
  text?: string
  toolName?: string
  toolInput?: Record<string, unknown>
  toolResult?: string
  toolUseId?: string
  /** Programming language (when type is "code"). */
  language?: string
  /** Base64-encoded image data (when type is "image"). */
  imageData?: string
  /** Image media type, e.g. "image/png" (when type is "image"). */
  mediaType?: string
  /** Image description generated by vision AI (when type is "image"). */
  imageDescription?: string
}

/** A single chat message with full metadata. */
export interface ChatMessage {
  id: ChatMessageId
  role: ChatRole
  content: ContentBlock[]
  timestamp: string
  branchId: BranchId
  parentMessageId?: ChatMessageId
  pinned: boolean
  tags: string[]
  tokenUsage?: TokenUsage
  model?: string
  apiDurationMs?: number
}

export interface TokenUsage {
  inputTokens: number
  outputTokens: number
  cacheReadTokens?: number
  cacheCreationTokens?: number
}

// ── Conversation & Branching ─────────────────────────────────────────────────

export interface Branch {
  id: BranchId
  label: string
  parentBranchId?: BranchId
  forkPointMessageId?: ChatMessageId
  createdAt: string
}

export interface Conversation {
  id: string
  title: string
  branches: Branch[]
  activeBranchId: BranchId
  messages: ChatMessage[]
  createdAt: string
  updatedAt: string
  totalTokenUsage: TokenUsage
  metadata: ConversationMetadata
}

export interface ConversationMetadata {
  cwd?: string
  gitBranch?: string
  modelsUsed: string[]
  totalToolCalls: number
  estimatedCostUsd: number
}

// ── Search Types ─────────────────────────────────────────────────────────────

export type SearchMode = 'fuzzy' | 'exact' | 'regex'

export interface ChatSearchOptions {
  query: string
  mode: SearchMode
  roles?: ChatRole[]
  branchId?: BranchId
  after?: string
  before?: string
  toolName?: string
  pinnedOnly?: boolean
  tags?: string[]
  limit?: number
}

export interface ChatSearchResult {
  message: ChatMessage
  score: number
  highlights: SearchHighlight[]
}

export interface SearchHighlight {
  line: string
  matchStart: number
  matchLength: number
}

// ── Analytics Types ──────────────────────────────────────────────────────────

export interface ConversationAnalytics {
  turnCount: number
  messageCounts: Record<ChatRole, number>
  tokenUsage: TokenUsage
  avgAssistantTokens: number
  avgApiLatencyMs: number
  toolUsageFrequency: Record<string, number>
  estimatedCostUsd: number
  durationMs: number
  modelBreakdown: ModelUsageBreakdown[]
  codeStats: CodeStats
  imageStats: ImageStats
}

export interface ModelUsageBreakdown {
  model: string
  messageCount: number
  tokenUsage: TokenUsage
  estimatedCostUsd: number
}

/** Statistics about code generated during the conversation. */
export interface CodeStats {
  totalSnippets: number
  languageBreakdown: Record<string, number>
  totalLinesOfCode: number
}

/** Statistics about images analyzed during the conversation. */
export interface ImageStats {
  totalImagesAnalyzed: number
  imagesWithDescriptions: number
}

// ── Export Types ──────────────────────────────────────────────────────────────

export type ExportFormat = 'markdown' | 'json' | 'text'

export interface ExportOptions {
  format: ExportFormat
  branchId?: BranchId
  includeSystemMessages?: boolean
  includeToolBlocks?: boolean
  includeTokenUsage?: boolean
  includeAnalytics?: boolean
  includeCode?: boolean
}

// ── Context Window Types ─────────────────────────────────────────────────────

export type MessagePriority = 'critical' | 'high' | 'medium' | 'low'

export interface ContextWindowConfig {
  maxTokens: number
  reserveForResponse: number
  overflowStrategy: 'truncate_oldest' | 'summarize' | 'drop_low_priority'
  protectedPriorities: MessagePriority[]
}

export interface ContextWindowResult {
  messages: ChatMessage[]
  totalTokens: number
  droppedCount: number
  wasTruncated: boolean
}

// ── Code Writer Types ────────────────────────────────────────────────────────

/** All languages the AI can write code in. */
export type ProgrammingLanguage =
  | 'typescript' | 'javascript' | 'python' | 'rust' | 'go'
  | 'java' | 'c' | 'cpp' | 'csharp' | 'swift'
  | 'kotlin' | 'ruby' | 'php' | 'html' | 'css'
  | 'sql' | 'bash' | 'powershell' | 'r' | 'dart'
  | 'scala' | 'lua' | 'haskell' | 'elixir'

/** Request to generate code. */
export interface CodeRequest {
  description: string
  language: ProgrammingLanguage
  context?: string
  style?: 'concise' | 'detailed' | 'production'
}

/** Result of code generation. */
export interface CodeResult {
  code: string
  language: ProgrammingLanguage
  explanation: string
  linesOfCode: number
  complexity: 'simple' | 'moderate' | 'complex'
}

/** Request to review code. */
export interface CodeReviewRequest {
  code: string
  language: ProgrammingLanguage
  focus?: ('bugs' | 'performance' | 'security' | 'style' | 'all')[]
}

/** Result of code review. */
export interface CodeReviewResult {
  issues: CodeIssue[]
  score: number
  summary: string
  improvedCode?: string
}

export interface CodeIssue {
  severity: 'error' | 'warning' | 'info'
  line?: number
  message: string
  suggestion?: string
}

// ── Image Analysis Types ─────────────────────────────────────────────────────

/** Request to analyze an image. */
export interface ImageAnalysisRequest {
  imageData: string
  mediaType: string
  question?: string
}

/** Result of image analysis. */
export interface ImageAnalysisResult {
  description: string
  objects: string[]
  colors: string[]
  text?: string
  sentiment?: string
  tags: string[]
}

// ── AI Brain Types ───────────────────────────────────────────────────────────

/** Configuration for the AI Brain. */
export interface AiBrainConfig {
  apiKey?: string
  model: string
  maxTokens: number
  temperature: number
  systemPrompt: string
}

/** A message in the format the Claude API expects. */
export interface ApiMessage {
  role: 'user' | 'assistant'
  content: string | ApiContentBlock[]
}

/**
 * Common interface that any brain (AiBrain, LocalBrain, or custom) must implement.
 * This allows AdvancedChat to work with any brain implementation.
 */
export interface BrainInterface {
  chat(userMessage: string): Promise<{ text: string; usage: TokenUsage; durationMs: number }>
  writeCode(request: CodeRequest): Promise<CodeResult>
  reviewCode(request: CodeReviewRequest): Promise<CodeReviewResult>
  analyzeImage(request: ImageAnalysisRequest): Promise<ImageAnalysisResult>
  getModel(): string
  setModel(model: string): void
  clearHistory(): void
}

export interface ApiContentBlock {
  type: 'text' | 'image'
  text?: string
  source?: {
    type: 'base64'
    media_type: string
    data: string
  }
}

// ╔═══════════════════════════════════════════════════════════════════════════════╗
// ║                                                                             ║
// ║  §2  SEARCH ENGINE — Find any message instantly                             ║
// ║                                                                             ║
// ║  WHY THIS WAS MADE:                                                         ║
// ║  In long AI conversations, finding a specific message is like finding a      ║
// ║  needle in a haystack. This search engine supports:                          ║
// ║    • Fuzzy search  — "fndfl" matches "findFile" (typo-tolerant)             ║
// ║    • Exact search  — literal string matching                                ║
// ║    • Regex search  — full regular expression power                          ║
// ║    • Relevance scoring — best matches appear first                          ║
// ║    • Highlighted snippets — shows exactly what matched                      ║
// ║    • Rich filters — by role, branch, date, tool, tags, pins                 ║
// ║                                                                             ║
// ╚═══════════════════════════════════════════════════════════════════════════════╝

function extractTextFromBlocks(blocks: ContentBlock[]): string {
  return blocks
    .map(block => {
      switch (block.type) {
        case 'text':
          return block.text ?? ''
        case 'code':
          return `[${block.language ?? 'code'}]\n${block.text ?? ''}`
        case 'tool_use':
          return `[Tool: ${block.toolName ?? 'unknown'}] ${JSON.stringify(block.toolInput ?? {})}`
        case 'tool_result':
          return block.toolResult ?? ''
        case 'image':
          return block.imageDescription ?? '[image]'
        default:
          return ''
      }
    })
    .filter(Boolean)
    .join('\n')
}

function escapeRegex(str: string): string {
  return str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

function buildPattern(query: string, mode: SearchMode): RegExp {
  switch (mode) {
    case 'exact':
      return new RegExp(escapeRegex(query), 'gi')
    case 'regex':
      try {
        return new RegExp(query, 'gi')
      } catch {
        return new RegExp(escapeRegex(query), 'gi')
      }
    case 'fuzzy': {
      const words = query.trim().split(/\s+/).map(w => escapeRegex(w))
      return new RegExp(words.join('.*'), 'gi')
    }
  }
}

function computeScore(text: string, pattern: RegExp, query: string): number {
  if (text.length === 0) return 0
  const matches = [...text.matchAll(new RegExp(pattern.source, pattern.flags))]
  if (matches.length === 0) return 0
  const density = Math.min(matches.length / (text.length / Math.max(query.length, 1)), 1)
  const exactMatches = [...text.matchAll(new RegExp(pattern.source, 'g'))]
  const exactBonus = exactMatches.length > 0 ? 0.1 : 0
  const lengthPenalty = text.length > 5000 ? 0.95 : 1
  return Math.min((density + exactBonus) * lengthPenalty, 1)
}

function buildHighlights(text: string, pattern: RegExp): SearchHighlight[] {
  const lines = text.split('\n')
  const highlights: SearchHighlight[] = []
  for (const line of lines) {
    const lineMatches = [...line.matchAll(new RegExp(pattern.source, pattern.flags))]
    for (const m of lineMatches) {
      if (m.index === undefined) continue
      highlights.push({ line, matchStart: m.index, matchLength: m[0].length })
    }
  }
  return highlights
}

function passesFilters(msg: ChatMessage, options: ChatSearchOptions): boolean {
  if (options.roles?.length && !options.roles.includes(msg.role)) return false
  if (options.branchId && msg.branchId !== options.branchId) return false
  if (options.after && msg.timestamp < options.after) return false
  if (options.before && msg.timestamp > options.before) return false
  if (options.pinnedOnly && !msg.pinned) return false
  if (options.tags?.length && !options.tags.some(tag => msg.tags.includes(tag))) return false
  if (options.toolName) {
    if (!msg.content.some(b => b.type === 'tool_use' && b.toolName === options.toolName)) return false
  }
  return true
}

/** Search through messages with relevance scoring and highlighting. */
export function searchMessages(messages: ChatMessage[], options: ChatSearchOptions): ChatSearchResult[] {
  const { query, mode = 'fuzzy', limit = 50 } = options
  if (!query.trim()) return []
  const pattern = buildPattern(query, mode)
  const results: ChatSearchResult[] = []
  for (const msg of messages) {
    if (!passesFilters(msg, options)) continue
    const text = extractTextFromBlocks(msg.content)
    if (!pattern.test(text)) { pattern.lastIndex = 0; continue }
    pattern.lastIndex = 0
    results.push({ message: msg, score: computeScore(text, pattern, query), highlights: buildHighlights(text, pattern) })
  }
  results.sort((a, b) => b.score !== a.score ? b.score - a.score : b.message.timestamp.localeCompare(a.message.timestamp))
  return results.slice(0, limit)
}

/** Search for messages that use a specific tool. */
export function searchByTool(messages: ChatMessage[], toolName: string, limit = 20): ChatSearchResult[] {
  return searchMessages(messages, { query: toolName, mode: 'exact', toolName, limit })
}

/** Get all pinned/bookmarked messages. */
export function getPinnedMessages(messages: ChatMessage[], branchId?: string): ChatMessage[] {
  return messages.filter(m => m.pinned && (branchId ? m.branchId === branchId : true))
}

// ╔═══════════════════════════════════════════════════════════════════════════════╗
// ║                                                                             ║
// ║  §3  ANALYTICS ENGINE — Token, cost & tool tracking                         ║
// ║                                                                             ║
// ║  WHY THIS WAS MADE:                                                         ║
// ║  AI API calls cost money and use tokens. This engine tracks everything:     ║
// ║    • Token usage (input, output, cache)                                     ║
// ║    • Estimated USD cost per model                                           ║
// ║    • Which tools are used most                                              ║
// ║    • Average response latency                                               ║
// ║    • Per-turn and per-model breakdowns                                      ║
// ║    • Code generation and image analysis statistics                          ║
// ║                                                                             ║
// ╚═══════════════════════════════════════════════════════════════════════════════╝

/**
 * Approximate cost per 1 000 tokens for popular models.
 * These are rough estimates — real pricing depends on the provider.
 * Last verified: 2025. See https://www.anthropic.com/pricing for current rates.
 */
const MODEL_COST_PER_1K: Record<string, { input: number; output: number }> = {
  'claude-opus-4-20250514': { input: 0.015, output: 0.075 },
  'claude-sonnet-4-20250514': { input: 0.003, output: 0.015 },
  'claude-3-5-sonnet-20241022': { input: 0.003, output: 0.015 },
  'claude-3-5-haiku-20241022': { input: 0.0008, output: 0.004 },
  'claude-3-opus-20240229': { input: 0.015, output: 0.075 },
  default: { input: 0.003, output: 0.015 },
}

function estimateCost(model: string | undefined, usage: TokenUsage): number {
  const rates = MODEL_COST_PER_1K[model ?? ''] ?? MODEL_COST_PER_1K['default']!
  return (usage.inputTokens / 1000) * rates.input + (usage.outputTokens / 1000) * rates.output
}

function emptyUsage(): TokenUsage {
  return { inputTokens: 0, outputTokens: 0, cacheReadTokens: 0, cacheCreationTokens: 0 }
}

function addUsage(a: TokenUsage, b: TokenUsage): TokenUsage {
  return {
    inputTokens: a.inputTokens + b.inputTokens,
    outputTokens: a.outputTokens + b.outputTokens,
    cacheReadTokens: (a.cacheReadTokens ?? 0) + (b.cacheReadTokens ?? 0),
    cacheCreationTokens: (a.cacheCreationTokens ?? 0) + (b.cacheCreationTokens ?? 0),
  }
}

/** Compute comprehensive conversation analytics including code & image stats. */
export function computeAnalytics(messages: ChatMessage[]): ConversationAnalytics {
  const empty: ConversationAnalytics = {
    turnCount: 0,
    messageCounts: { user: 0, assistant: 0, system: 0, tool: 0 },
    tokenUsage: emptyUsage(),
    avgAssistantTokens: 0,
    avgApiLatencyMs: 0,
    toolUsageFrequency: {},
    estimatedCostUsd: 0,
    durationMs: 0,
    modelBreakdown: [],
    codeStats: { totalSnippets: 0, languageBreakdown: {}, totalLinesOfCode: 0 },
    imageStats: { totalImagesAnalyzed: 0, imagesWithDescriptions: 0 },
  }
  if (messages.length === 0) return empty

  const counts: Record<ChatRole, number> = { user: 0, assistant: 0, system: 0, tool: 0 }
  let totalUsage = emptyUsage()
  let assistantOut = 0, assistantCount = 0, latencySum = 0, latencyCount = 0
  const toolFreq: Record<string, number> = {}
  const modelMap = new Map<string, { messageCount: number; tokenUsage: TokenUsage; estimatedCostUsd: number }>()
  let turnCount = 0
  const codeStats: CodeStats = { totalSnippets: 0, languageBreakdown: {}, totalLinesOfCode: 0 }
  const imageStats: ImageStats = { totalImagesAnalyzed: 0, imagesWithDescriptions: 0 }

  for (const msg of messages) {
    counts[msg.role] = (counts[msg.role] ?? 0) + 1
    if (msg.role === 'user') turnCount++
    if (msg.tokenUsage) totalUsage = addUsage(totalUsage, msg.tokenUsage)

    if (msg.role === 'assistant') {
      assistantCount++
      if (msg.tokenUsage) assistantOut += msg.tokenUsage.outputTokens
      if (msg.apiDurationMs !== undefined) { latencySum += msg.apiDurationMs; latencyCount++ }
      const model = msg.model ?? 'unknown'
      const e = modelMap.get(model) ?? { messageCount: 0, tokenUsage: emptyUsage(), estimatedCostUsd: 0 }
      e.messageCount++
      if (msg.tokenUsage) { e.tokenUsage = addUsage(e.tokenUsage, msg.tokenUsage); e.estimatedCostUsd += estimateCost(model, msg.tokenUsage) }
      modelMap.set(model, e)
    }

    for (const block of msg.content) {
      if (block.type === 'tool_use' && block.toolName) toolFreq[block.toolName] = (toolFreq[block.toolName] ?? 0) + 1
      if (block.type === 'code') {
        codeStats.totalSnippets++
        const lang = block.language ?? 'unknown'
        codeStats.languageBreakdown[lang] = (codeStats.languageBreakdown[lang] ?? 0) + 1
        codeStats.totalLinesOfCode += (block.text ?? '').split('\n').length
      }
      if (block.type === 'image') {
        imageStats.totalImagesAnalyzed++
        if (block.imageDescription) imageStats.imagesWithDescriptions++
      }
    }
  }

  const sorted = [...messages].sort((a, b) => a.timestamp.localeCompare(b.timestamp))
  const durationMs = new Date(sorted[sorted.length - 1]!.timestamp).getTime() - new Date(sorted[0]!.timestamp).getTime()
  const modelBreakdown = [...modelMap.entries()].map(([model, data]) => ({ model, ...data }))
  const costUsd = modelBreakdown.reduce((s, m) => s + m.estimatedCostUsd, 0)

  return {
    turnCount,
    messageCounts: counts,
    tokenUsage: totalUsage,
    avgAssistantTokens: assistantCount > 0 ? Math.round(assistantOut / assistantCount) : 0,
    avgApiLatencyMs: latencyCount > 0 ? Math.round(latencySum / latencyCount) : 0,
    toolUsageFrequency: toolFreq,
    estimatedCostUsd: Math.round(costUsd * 1_000_000) / 1_000_000,
    durationMs: Math.max(durationMs, 0),
    modelBreakdown,
    codeStats,
    imageStats,
  }
}

/** Top-N most frequently used tools. */
export function getTopTools(messages: ChatMessage[], n = 10): Array<{ toolName: string; count: number }> {
  const freq: Record<string, number> = {}
  for (const msg of messages) for (const b of msg.content) if (b.type === 'tool_use' && b.toolName) freq[b.toolName] = (freq[b.toolName] ?? 0) + 1
  return Object.entries(freq).map(([toolName, count]) => ({ toolName, count })).sort((a, b) => b.count - a.count).slice(0, n)
}

/** Per-turn breakdown (user → assistant pair). */
export function getTurnBreakdown(messages: ChatMessage[]) {
  const sorted = [...messages].sort((a, b) => a.timestamp.localeCompare(b.timestamp))
  const turns: Array<{ turnIndex: number; userMessage: ChatMessage; assistantMessages: ChatMessage[]; turnTokens: TokenUsage; turnDurationMs: number }> = []
  let current: (typeof turns)[number] | null = null
  let idx = 0
  for (const msg of sorted) {
    if (msg.role === 'user') {
      if (current) turns.push(current)
      current = { turnIndex: idx++, userMessage: msg, assistantMessages: [], turnTokens: msg.tokenUsage ? { ...msg.tokenUsage } : emptyUsage(), turnDurationMs: 0 }
    } else if (msg.role === 'assistant' && current) {
      current.assistantMessages.push(msg)
      if (msg.tokenUsage) current.turnTokens = addUsage(current.turnTokens, msg.tokenUsage)
      current.turnDurationMs = new Date(msg.timestamp).getTime() - new Date(current.userMessage.timestamp).getTime()
    }
  }
  if (current) turns.push(current)
  return turns
}

// ╔═══════════════════════════════════════════════════════════════════════════════╗
// ║                                                                             ║
// ║  §4  EXPORT ENGINE — Markdown / JSON / Text output                          ║
// ║                                                                             ║
// ║  WHY THIS WAS MADE:                                                         ║
// ║  Users need to save, share, or review conversations outside the chat.       ║
// ║  This engine converts messages into three formats:                          ║
// ║    • Markdown — great for docs, READMEs, sharing with teams                 ║
// ║    • JSON     — structured data for APIs, archives, automation              ║
// ║    • Text     — simple plain text for logging, pasting, terminal            ║
// ║                                                                             ║
// ╚═══════════════════════════════════════════════════════════════════════════════╝

function roleLabel(r: string): string { return ({ user: 'User', assistant: 'Assistant', system: 'System', tool: 'Tool' }[r]) ?? r }

function fmtTimestamp(iso: string): string {
  try { return new Date(iso).toLocaleString('en-US', { year: 'numeric', month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit', second: '2-digit', hour12: false }) }
  catch { return iso }
}

function fmtTokens(u: TokenUsage): string {
  const p = [`in: ${u.inputTokens}`, `out: ${u.outputTokens}`]
  if (u.cacheReadTokens) p.push(`cache_read: ${u.cacheReadTokens}`)
  if (u.cacheCreationTokens) p.push(`cache_create: ${u.cacheCreationTokens}`)
  return p.join(', ')
}

function blockMd(b: ContentBlock, tools: boolean, code: boolean): string {
  switch (b.type) {
    case 'text': return b.text ?? ''
    case 'code':
      if (!code) return ''
      return `\`\`\`${b.language ?? ''}\n${b.text ?? ''}\n\`\`\``
    case 'tool_use':
      if (!tools) return ''
      return `\`\`\`tool_use [${b.toolName ?? 'unknown'}]\n${JSON.stringify(b.toolInput ?? {}, null, 2)}\n\`\`\``
    case 'tool_result':
      if (!tools) return ''
      return `\`\`\`tool_result\n${b.toolResult ?? '(empty)'}\n\`\`\``
    case 'image':
      return b.imageDescription ? `*🖼 Image: ${b.imageDescription}*` : '*🖼 [image]*'
    default: return ''
  }
}

function blockTxt(b: ContentBlock, tools: boolean, code: boolean): string {
  switch (b.type) {
    case 'text': return b.text ?? ''
    case 'code':
      if (!code) return ''
      return `[Code: ${b.language ?? 'unknown'}]\n${b.text ?? ''}`
    case 'tool_use':
      if (!tools) return ''
      return `[Tool: ${b.toolName ?? 'unknown'}] ${JSON.stringify(b.toolInput ?? {})}`
    case 'tool_result':
      if (!tools) return ''
      return `[Tool Result] ${b.toolResult ?? '(empty)'}`
    case 'image':
      return b.imageDescription ? `[Image: ${b.imageDescription}]` : '[image]'
    default: return ''
  }
}

function filterMsgs(messages: ChatMessage[], o: ExportOptions): ChatMessage[] {
  let f = messages
  if (o.branchId) f = f.filter(m => m.branchId === o.branchId)
  if (!o.includeSystemMessages) f = f.filter(m => m.role !== 'system')
  return [...f].sort((a, b) => a.timestamp.localeCompare(b.timestamp))
}

function expMd(messages: ChatMessage[], o: ExportOptions): string {
  const f = filterMsgs(messages, o), tools = o.includeToolBlocks ?? true, code = o.includeCode ?? true
  const lines = ['# 🤖 AI Conversation Export', '']
  for (const m of f) {
    lines.push(`## ${roleLabel(m.role)} — ${fmtTimestamp(m.timestamp)}`)
    if (m.pinned) lines.push('📌 *Pinned*')
    if (m.tags.length) lines.push(`Tags: ${m.tags.map(t => `\`${t}\``).join(', ')}`)
    if (m.model) lines.push(`Model: \`${m.model}\``)
    lines.push('')
    for (const b of m.content) { const r = blockMd(b, tools, code); if (r) lines.push(r, '') }
    if (o.includeTokenUsage && m.tokenUsage) {
      lines.push(`> Tokens: ${fmtTokens(m.tokenUsage)}`)
      if (m.apiDurationMs !== undefined) lines.push(`> Latency: ${m.apiDurationMs}ms`)
      lines.push('')
    }
    lines.push('---', '')
  }
  if (o.includeAnalytics) {
    const a = computeAnalytics(f)
    lines.push('## 📊 Analytics', '', '| Metric | Value |', '| --- | --- |',
      `| Turns | ${a.turnCount} |`,
      `| Messages | user: ${a.messageCounts.user}, assistant: ${a.messageCounts.assistant}, system: ${a.messageCounts.system}, tool: ${a.messageCounts.tool} |`,
      `| Tokens | in: ${a.tokenUsage.inputTokens}, out: ${a.tokenUsage.outputTokens} |`,
      `| Cost | $${a.estimatedCostUsd.toFixed(4)} |`,
      `| Duration | ${Math.round(a.durationMs / 1000)}s |`,
      `| Code snippets | ${a.codeStats.totalSnippets} (${a.codeStats.totalLinesOfCode} lines) |`,
      `| Images analyzed | ${a.imageStats.totalImagesAnalyzed} |`, '')
  }
  return lines.join('\n')
}

function expJson(messages: ChatMessage[], o: ExportOptions): string {
  const f = filterMsgs(messages, o)
  const payload: Record<string, unknown> = {
    exportedAt: new Date().toISOString(), messageCount: f.length,
    messages: f.map(m => ({
      id: m.id, role: m.role, timestamp: m.timestamp, branchId: m.branchId, pinned: m.pinned, tags: m.tags, model: m.model,
      content: o.includeToolBlocks ? m.content : m.content.filter(b => b.type === 'text' || b.type === 'image' || b.type === 'code'),
      ...(o.includeTokenUsage && m.tokenUsage ? { tokenUsage: m.tokenUsage, apiDurationMs: m.apiDurationMs } : {}),
    })),
  }
  if (o.includeAnalytics) payload['analytics'] = computeAnalytics(f)
  return JSON.stringify(payload, null, 2)
}

function expTxt(messages: ChatMessage[], o: ExportOptions): string {
  const f = filterMsgs(messages, o), tools = o.includeToolBlocks ?? true, code = o.includeCode ?? true
  const lines = ['=== 🤖 AI Conversation Export ===', '']
  for (const m of f) {
    const hdr = `[${fmtTimestamp(m.timestamp)}] ${roleLabel(m.role)}${m.model ? ` (${m.model})` : ''}${m.pinned ? ' 📌' : ''}`
    lines.push(hdr, '-'.repeat(hdr.length))
    for (const b of m.content) { const r = blockTxt(b, tools, code); if (r) lines.push(r) }
    if (o.includeTokenUsage && m.tokenUsage) lines.push(`  [Tokens: ${fmtTokens(m.tokenUsage)}]`)
    lines.push('')
  }
  return lines.join('\n')
}

/** Export conversation to Markdown, JSON, or plain text. */
export function exportConversation(messages: ChatMessage[], options: ExportOptions): string {
  const fmt = options.format ?? 'markdown'
  switch (fmt) {
    case 'markdown': return expMd(messages, options)
    case 'json': return expJson(messages, options)
    case 'text': return expTxt(messages, options)
    default: { const _exhaustive: never = fmt; throw new Error(`Unsupported format: ${_exhaustive}`) }
  }
}

// ╔═══════════════════════════════════════════════════════════════════════════════╗
// ║                                                                             ║
// ║  §5  CODE WRITER — Generate, review & fix code                              ║
// ║                                                                             ║
// ║  WHY THIS WAS MADE:                                                         ║
// ║  A smart AI must be able to write code. This section provides:              ║
// ║    • Code generation in 24 languages with templates & patterns              ║
// ║    • Code review that finds bugs, security issues, and style problems       ║
// ║    • Code explanation that breaks down what code does                        ║
// ║    • Language detection from source code                                    ║
// ║    • Line counting and complexity analysis                                   ║
// ║  The AI Brain (§7) uses this to power its code-writing capabilities.        ║
// ║                                                                             ║
// ╚═══════════════════════════════════════════════════════════════════════════════╝

/** File extensions and comment syntax per language. */
const LANG_INFO: Record<string, { ext: string; comment: string; block?: [string, string] }> = {
  typescript: { ext: '.ts', comment: '//', block: ['/*', '*/'] },
  javascript: { ext: '.js', comment: '//', block: ['/*', '*/'] },
  python: { ext: '.py', comment: '#', block: ['"""', '"""'] },
  rust: { ext: '.rs', comment: '//', block: ['/*', '*/'] },
  go: { ext: '.go', comment: '//', block: ['/*', '*/'] },
  java: { ext: '.java', comment: '//', block: ['/*', '*/'] },
  c: { ext: '.c', comment: '//', block: ['/*', '*/'] },
  cpp: { ext: '.cpp', comment: '//', block: ['/*', '*/'] },
  csharp: { ext: '.cs', comment: '//', block: ['/*', '*/'] },
  swift: { ext: '.swift', comment: '//', block: ['/*', '*/'] },
  kotlin: { ext: '.kt', comment: '//', block: ['/*', '*/'] },
  ruby: { ext: '.rb', comment: '#', block: ['=begin', '=end'] },
  php: { ext: '.php', comment: '//', block: ['/*', '*/'] },
  html: { ext: '.html', comment: '', block: ['<!--', '-->'] },
  css: { ext: '.css', comment: '', block: ['/*', '*/'] },
  sql: { ext: '.sql', comment: '--' },
  bash: { ext: '.sh', comment: '#' },
  powershell: { ext: '.ps1', comment: '#', block: ['<#', '#>'] },
  r: { ext: '.R', comment: '#' },
  dart: { ext: '.dart', comment: '//', block: ['/*', '*/'] },
  scala: { ext: '.scala', comment: '//', block: ['/*', '*/'] },
  lua: { ext: '.lua', comment: '--', block: ['--[[', ']]'] },
  haskell: { ext: '.hs', comment: '--', block: ['{-', '-}'] },
  elixir: { ext: '.ex', comment: '#' },
}

/** Starter templates for common code patterns per language. */
const CODE_TEMPLATES: Record<string, Record<string, string>> = {
  typescript: {
    function: 'export function {{name}}({{params}}): {{returnType}} {\n  {{body}}\n}',
    class: 'export class {{name}} {\n  constructor({{params}}) {\n    {{body}}\n  }\n}',
    interface: 'export interface {{name}} {\n  {{body}}\n}',
    test: 'describe("{{name}}", () => {\n  it("should {{description}}", () => {\n    {{body}}\n  })\n})',
    api: 'export async function {{name}}(req: Request): Promise<Response> {\n  {{body}}\n  return new Response(JSON.stringify({ ok: true }), { status: 200 })\n}',
  },
  python: {
    function: 'def {{name}}({{params}}){{returnType}}:\n    """{{description}}"""\n    {{body}}',
    class: 'class {{name}}:\n    """{{description}}"""\n\n    def __init__(self, {{params}}):\n        {{body}}',
    test: 'def test_{{name}}():\n    """{{description}}"""\n    {{body}}\n    assert result == expected',
    api: '@app.route("/{{name}}", methods=["GET"])\ndef {{name}}():\n    """{{description}}"""\n    {{body}}\n    return jsonify({"ok": True})',
    dataclass: 'from dataclasses import dataclass\n\n@dataclass\nclass {{name}}:\n    """{{description}}"""\n    {{body}}',
  },
  rust: {
    function: 'pub fn {{name}}({{params}}) -> {{returnType}} {\n    {{body}}\n}',
    struct: 'pub struct {{name}} {\n    {{body}}\n}\n\nimpl {{name}} {\n    pub fn new({{params}}) -> Self {\n        Self { {{body}} }\n    }\n}',
    test: '#[cfg(test)]\nmod tests {\n    use super::*;\n\n    #[test]\n    fn test_{{name}}() {\n        {{body}}\n    }\n}',
    enum_: 'pub enum {{name}} {\n    {{body}}\n}',
  },
  go: {
    function: 'func {{name}}({{params}}) {{returnType}} {\n\t{{body}}\n}',
    struct: 'type {{name}} struct {\n\t{{body}}\n}\n\nfunc New{{name}}({{params}}) *{{name}} {\n\treturn &{{name}}{{{body}}}\n}',
    test: 'func Test{{name}}(t *testing.T) {\n\t{{body}}\n}',
    handler: 'func {{name}}Handler(w http.ResponseWriter, r *http.Request) {\n\t{{body}}\n\tjson.NewEncoder(w).Encode(map[string]bool{"ok": true})\n}',
  },
  java: {
    class: 'public class {{name}} {\n    {{body}}\n\n    public {{name}}({{params}}) {\n        {{body}}\n    }\n}',
    method: 'public {{returnType}} {{name}}({{params}}) {\n    {{body}}\n}',
    test: '@Test\npublic void test{{name}}() {\n    {{body}}\n    assertEquals(expected, result);\n}',
    interface: 'public interface {{name}} {\n    {{body}}\n}',
  },
}

/** Detect the programming language from source code. */
export function detectLanguage(code: string): ProgrammingLanguage {
  const indicators: Array<[ProgrammingLanguage, RegExp[]]> = [
    ['typescript', [/:\s*(string|number|boolean|void|any)\b/, /interface\s+\w+/, /import\s+type\s/]],
    ['python', [/def\s+\w+\s*\(/, /import\s+\w+/, /if\s+__name__\s*==\s*['"]__main__['"]/]],
    ['rust', [/fn\s+\w+\s*\(/, /let\s+mut\s/, /impl\s+\w+/, /pub\s+fn\s/]],
    ['go', [/func\s+\w+\s*\(/, /package\s+\w+/, /import\s+\(/, /:=\s/]],
    ['java', [/public\s+class\s/, /System\.out\.print/, /public\s+static\s+void\s+main/]],
    ['csharp', [/using\s+System/, /namespace\s+\w+/, /public\s+class\s/, /Console\.Write/]],
    ['swift', [/func\s+\w+\s*\(.*\)\s*->/, /let\s+\w+\s*:\s*\w+/, /import\s+Foundation/]],
    ['kotlin', [/fun\s+\w+\s*\(/, /val\s+\w+\s*[:=]/, /package\s+\w+\.\w+/]],
    ['ruby', [/def\s+\w+/, /end\s*$/, /require\s+['"]/, /class\s+\w+\s*<?\s/]],
    ['php', [/<\?php/, /\$\w+\s*=/, /function\s+\w+\s*\(/]],
    ['html', [/<html/, /<div/, /<body/, /<!DOCTYPE/i]],
    ['css', [/[.#]\w+\s*\{/, /@media\s/, /:\s*(flex|grid|block|none)\s*;/]],
    ['sql', [/SELECT\s+/i, /CREATE\s+TABLE/i, /INSERT\s+INTO/i]],
    ['bash', [/^#!/, /echo\s+/, /if\s+\[\[?\s/]],
    ['lua', [/local\s+\w+\s*=/, /function\s+\w+\s*\(/, /end\s*$/]],
    ['haskell', [/module\s+\w+/, /::\s*/, /import\s+qualified/]],
    ['elixir', [/defmodule\s/, /def\s+\w+\s*do/, /\|>\s/]],
    ['dart', [/void\s+main\s*\(/, /Widget\s+build/, /import\s+'package:/]],
    ['scala', [/object\s+\w+/, /def\s+\w+\s*\(/, /val\s+\w+\s*:\s/]],
    ['javascript', [/const\s+\w+\s*=/, /function\s+\w+\s*\(/, /=>\s*\{/, /require\s*\(/]],
  ]
  for (const [lang, patterns] of indicators) {
    const matches = patterns.filter(p => p.test(code)).length
    if (matches >= 2) return lang
  }
  return 'javascript'
}

/** Count lines of code (excluding blank lines and comments). */
export function countLinesOfCode(code: string, language: ProgrammingLanguage): { total: number; code: number; blank: number; comment: number } {
  const lines = code.split('\n')
  const info = LANG_INFO[language]
  let codeLines = 0, blank = 0, comment = 0, inBlock = false
  const blockStart = info?.block?.[0], blockEnd = info?.block?.[1]

  for (const line of lines) {
    const trimmed = line.trim()
    if (!trimmed) { blank++; continue }
    if (inBlock) { comment++; if (blockEnd && trimmed.includes(blockEnd)) inBlock = false; continue }
    if (blockStart && trimmed.startsWith(blockStart)) { comment++; if (blockEnd && !trimmed.includes(blockEnd)) inBlock = true; continue }
    if (info?.comment && trimmed.startsWith(info.comment)) { comment++; continue }
    codeLines++
  }
  return { total: lines.length, code: codeLines, blank, comment }
}

/** Estimate complexity of code. */
export function estimateComplexity(code: string): 'simple' | 'moderate' | 'complex' {
  const lines = code.split('\n').length
  const nesting = Math.max(...code.split('\n').map(l => l.search(/\S/)).filter(n => n >= 0)) / 2
  const branches = (code.match(/\b(if|else|switch|case|for|while|try|catch)\b/g) || []).length
  const score = lines * 0.3 + nesting * 2 + branches * 1.5
  if (score < 15) return 'simple'
  if (score < 50) return 'moderate'
  return 'complex'
}

/** Get a code template for a specific language and pattern. */
export function getCodeTemplate(language: ProgrammingLanguage, pattern: string): string | undefined {
  return CODE_TEMPLATES[language]?.[pattern]
}

/** Get language info (extension, comment syntax). */
export function getLanguageInfo(language: ProgrammingLanguage) {
  return LANG_INFO[language] ?? { ext: '.txt', comment: '//' }
}

/** Format code with consistent indentation. */
export function formatCode(code: string, indentSize = 2): string {
  const indent = ' '.repeat(indentSize)
  let level = 0
  return code.split('\n').map(line => {
    const trimmed = line.trim()
    if (!trimmed) return ''
    if (trimmed.startsWith('}') || trimmed.startsWith(')') || trimmed.startsWith(']')) level = Math.max(0, level - 1)
    const result = indent.repeat(level) + trimmed
    if (trimmed.endsWith('{') || trimmed.endsWith('(') || trimmed.endsWith('[')) level++
    return result
  }).join('\n')
}

// ╔═══════════════════════════════════════════════════════════════════════════════╗
// ║                                                                             ║
// ║  §6  IMAGE ANALYZER — Describe & understand photos                          ║
// ║                                                                             ║
// ║  WHY THIS WAS MADE:                                                         ║
// ║  Like Claude Opus 4.6, a smart AI should understand images. This section:   ║
// ║    • Validates image data and formats                                       ║
// ║    • Builds vision API requests with images + questions                      ║
// ║    • Processes analysis results into structured data                         ║
// ║    • Supports PNG, JPEG, GIF, and WebP images                               ║
// ║    • Creates image content blocks for conversations                          ║
// ║  The AI Brain (§7) sends these to the Claude Vision API.                    ║
// ║                                                                             ║
// ╚═══════════════════════════════════════════════════════════════════════════════╝

const SUPPORTED_IMAGE_TYPES = ['image/png', 'image/jpeg', 'image/gif', 'image/webp'] as const

/** Check if a media type is supported for image analysis. */
export function isSupportedImageType(mediaType: string): boolean {
  return (SUPPORTED_IMAGE_TYPES as readonly string[]).includes(mediaType)
}

/** Validate base64 image data. Returns true if the data looks like valid base64. */
export function validateImageData(data: string): boolean {
  if (!data || data.length === 0) return false
  if (data.length > 20_000_000) return false // ~15MB decoded (20M base64 chars ≈ 15MB raw bytes)
  return /^[A-Za-z0-9+/]+=*$/.test(data.replace(/\s/g, ''))
}

/** Estimate image file size from base64 data (in bytes). */
export function estimateImageSize(base64Data: string): number {
  const cleanData = base64Data.replace(/\s/g, '')
  return Math.floor(cleanData.length * 0.75)
}

/** Build a vision API content block for an image. */
export function buildImageContentBlock(imageData: string, mediaType: string, question?: string): ApiContentBlock[] {
  const blocks: ApiContentBlock[] = [
    { type: 'image', source: { type: 'base64', media_type: mediaType, data: imageData } },
  ]
  if (question) {
    blocks.push({ type: 'text', text: question })
  } else {
    blocks.push({ type: 'text', text: 'Describe this image in detail. What do you see? Include objects, colors, text, people, actions, and any other notable elements.' })
  }
  return blocks
}

/** Create a ChatMessage content block for an analyzed image. */
export function createImageBlock(imageData: string, mediaType: string, description?: string): ContentBlock {
  return {
    type: 'image',
    imageData,
    mediaType,
    imageDescription: description,
  }
}

/** Parse a text description into structured image analysis. */
export function parseImageAnalysis(description: string): ImageAnalysisResult {
  const colorPatterns = /\b(red|blue|green|yellow|orange|purple|pink|black|white|gray|grey|brown|cyan|magenta|gold|silver|beige|navy|teal|maroon|olive|coral|salmon|lavender|turquoise|indigo|violet)\b/gi
  const colors = [...new Set((description.match(colorPatterns) ?? []).map(c => c.toLowerCase()))]

  const objectPatterns = /\b(person|people|man|woman|child|dog|cat|car|tree|building|house|table|chair|phone|computer|book|flower|mountain|sky|sun|moon|water|road|door|window|wall|lamp|clock|cup|bottle|bag|hat|shirt|shoe|hand|face|eye|cloud|bird|fish|boat|airplane|train|bridge|park|garden|street|sign|light|shadow)\b/gi
  const objects = [...new Set((description.match(objectPatterns) ?? []).map(o => o.toLowerCase()))]

  const textMatch = description.match(/text\s+(?:that\s+)?(?:reads?|says?|shows?)\s*[:"]?\s*["']?([^"'\n.]+)/i)
  const text = textMatch?.[1]?.trim()

  const sentimentWords = { positive: /\b(happy|beautiful|bright|cheerful|peaceful|stunning|elegant|vibrant|warm|inviting|cozy)\b/i, negative: /\b(dark|gloomy|sad|lonely|broken|damaged|dirty|ugly|scary|ominous|bleak)\b/i }
  const posCount = (description.match(sentimentWords.positive) ?? []).length
  const negCount = (description.match(sentimentWords.negative) ?? []).length
  const sentiment = posCount > negCount ? 'positive' : negCount > posCount ? 'negative' : 'neutral'

  const tags = [...objects.slice(0, 5), ...colors.slice(0, 3)]
  if (text) tags.push('has-text')
  if (description.toLowerCase().includes('photo')) tags.push('photograph')
  if (description.toLowerCase().includes('screenshot')) tags.push('screenshot')
  if (description.toLowerCase().includes('diagram')) tags.push('diagram')
  if (description.toLowerCase().includes('chart') || description.toLowerCase().includes('graph')) tags.push('data-visualization')

  return { description, objects, colors, text, sentiment, tags }
}

// ╔═══════════════════════════════════════════════════════════════════════════════╗
// ║                                                                             ║
// ║  §7  AI BRAIN — Core intelligence (Claude API)                              ║
// ║                                                                             ║
// ║  WHY THIS WAS MADE:                                                         ║
// ║  This is the thinking core of the AI. It:                                   ║
// ║    • Connects to the Claude API for intelligence                            ║
// ║    • Sends messages and receives responses                                  ║
// ║    • Generates code using the Code Writer (§5)                              ║
// ║    • Analyzes images using the Image Analyzer (§6)                          ║
// ║    • Manages system prompts for different tasks                             ║
// ║    • Handles errors and retries gracefully                                  ║
// ║  This is what makes the AI "smart" — it's the connection to Claude.         ║
// ║                                                                             ║
// ╚═══════════════════════════════════════════════════════════════════════════════╝

const DEFAULT_SYSTEM_PROMPT = `You are an advanced AI assistant with expertise in:
- Writing high-quality code in 24+ programming languages
- Analyzing and describing images in detail
- Reviewing code for bugs, security issues, and best practices
- Explaining complex technical concepts clearly
- Problem-solving and architectural design

You are precise, helpful, and always provide working code with clear explanations.
When writing code, follow best practices for the language and include comments.
When analyzing images, be thorough and descriptive.`

const CODE_SYSTEM_PROMPT = `You are an expert software engineer. Write clean, production-quality code.
Follow these rules:
- Use proper types and error handling
- Include brief, useful comments
- Follow the language's naming conventions and idioms
- Make code readable and maintainable
- Handle edge cases
Respond ONLY with code inside a code block. Add a brief explanation after the code block.`

const IMAGE_SYSTEM_PROMPT = `You are a vision AI expert. Analyze images thoroughly.
Describe:
- Main subjects and objects
- Colors and visual composition
- Any text visible in the image
- Actions or activities happening
- Overall mood and context
- Notable details others might miss
Be specific and structured in your descriptions.`

const CODE_REVIEW_SYSTEM_PROMPT = `You are a senior code reviewer. Review code for:
- Bugs and logic errors
- Security vulnerabilities
- Performance issues
- Code style and readability
- Best practices for the language
Format your review as a list of issues, each with severity (error/warning/info), the line number if applicable, the problem, and a suggested fix.
End with an overall score from 0-100 and a brief summary.`

/**
 * The AI Brain — connects to Claude API for intelligence.
 *
 * This class handles all API communication. It can:
 *  - Chat: send messages and get AI responses
 *  - Write code: generate code in any supported language
 *  - Analyze images: describe and understand photos
 *  - Review code: find bugs, security issues, style problems
 */
export class AiBrain {
  private config: AiBrainConfig
  private conversationHistory: ApiMessage[] = []

  constructor(config?: Partial<AiBrainConfig>) {
    this.config = {
      model: config?.model ?? 'claude-sonnet-4-20250514',
      maxTokens: config?.maxTokens ?? 8192,
      temperature: config?.temperature ?? 0.7,
      systemPrompt: config?.systemPrompt ?? DEFAULT_SYSTEM_PROMPT,
      apiKey: config?.apiKey,
    }
  }

  /** Get the current model being used. */
  getModel(): string { return this.config.model }

  /** Switch to a different model. */
  setModel(model: string): void { this.config.model = model }

  /** Clear conversation history (start fresh). */
  clearHistory(): void { this.conversationHistory = [] }

  /**
   * Send a chat message to the AI and get a response.
   * Uses the Anthropic Claude API via HTTP.
   */
  async chat(userMessage: string): Promise<{ text: string; usage: TokenUsage; durationMs: number }> {
    this.conversationHistory.push({ role: 'user', content: userMessage })
    const start = Date.now()

    const response = await this.callApi(this.config.systemPrompt, this.conversationHistory)

    const durationMs = Date.now() - start
    this.conversationHistory.push({ role: 'assistant', content: response.text })
    return { text: response.text, usage: response.usage, durationMs }
  }

  /** Ask the AI to write code. */
  async writeCode(request: CodeRequest): Promise<CodeResult> {
    const prompt = `Write ${request.style ?? 'production'}-quality ${request.language} code for: ${request.description}${request.context ? `\n\nContext: ${request.context}` : ''}`
    const start = Date.now()
    const response = await this.callApi(CODE_SYSTEM_PROMPT, [{ role: 'user', content: prompt }])
    const durationMs = Date.now() - start

    // Extract code from response
    const codeMatch = response.text.match(/```(?:\w+)?\n([\s\S]*?)```/)
    const code = codeMatch?.[1]?.trim() ?? response.text
    const explanation = response.text.replace(/```[\s\S]*?```/g, '').trim()

    return {
      code,
      language: request.language,
      explanation: explanation || `Generated ${request.language} code for: ${request.description}`,
      linesOfCode: code.split('\n').length,
      complexity: estimateComplexity(code),
    }
  }

  /** Ask the AI to review code. */
  async reviewCode(request: CodeReviewRequest): Promise<CodeReviewResult> {
    const focus = request.focus?.join(', ') ?? 'all aspects'
    const prompt = `Review this ${request.language} code, focusing on ${focus}:\n\n\`\`\`${request.language}\n${request.code}\n\`\`\``
    const response = await this.callApi(CODE_REVIEW_SYSTEM_PROMPT, [{ role: 'user', content: prompt }])

    return parseCodeReview(response.text)
  }

  /** Ask the AI to analyze an image. */
  async analyzeImage(request: ImageAnalysisRequest): Promise<ImageAnalysisResult> {
    if (!isSupportedImageType(request.mediaType)) {
      throw new Error(`Unsupported image type: ${request.mediaType}. Supported: ${SUPPORTED_IMAGE_TYPES.join(', ')}`)
    }
    if (!validateImageData(request.imageData)) {
      throw new Error('Invalid image data. Ensure it is valid base64-encoded image data.')
    }

    const blocks = buildImageContentBlock(request.imageData, request.mediaType, request.question)
    const response = await this.callApi(IMAGE_SYSTEM_PROMPT, [{ role: 'user', content: blocks }])

    return parseImageAnalysis(response.text)
  }

  /** Low-level API call to Claude. */
  private async callApi(
    systemPrompt: string,
    messages: ApiMessage[],
  ): Promise<{ text: string; usage: TokenUsage }> {
    const apiKey = this.config.apiKey ?? this.getApiKeyFromEnv()
    if (!apiKey) {
      throw new Error(
        'No API key provided. Set ANTHROPIC_API_KEY environment variable or pass apiKey in config.\n' +
        'Get your key at: https://console.anthropic.com/settings/keys'
      )
    }

    const body = JSON.stringify({
      model: this.config.model,
      max_tokens: this.config.maxTokens,
      temperature: this.config.temperature,
      system: systemPrompt,
      messages,
    })

    const response = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': apiKey,
        'anthropic-version': '2023-06-01',
      },
      body,
    })

    if (!response.ok) {
      const errorText = await response.text()
      throw new Error(`Claude API error (${response.status}): ${errorText}`)
    }

    const data = await response.json() as {
      content: Array<{ type: string; text?: string }>
      usage: { input_tokens: number; output_tokens: number; cache_read_input_tokens?: number; cache_creation_input_tokens?: number }
    }

    const text = data.content
      .filter((b: { type: string }) => b.type === 'text')
      .map((b: { text?: string }) => b.text ?? '')
      .join('')

    return {
      text,
      usage: {
        inputTokens: data.usage.input_tokens,
        outputTokens: data.usage.output_tokens,
        cacheReadTokens: data.usage.cache_read_input_tokens ?? 0,
        cacheCreationTokens: data.usage.cache_creation_input_tokens ?? 0,
      },
    }
  }

  /** Try to get API key from environment. */
  private getApiKeyFromEnv(): string | undefined {
    try {
      // Access process.env dynamically to avoid compile-time dependency on @types/node
      const g = globalThis as Record<string, unknown>
      const proc = g['process'] as { env?: Record<string, string | undefined> } | undefined
      return proc?.env?.['ANTHROPIC_API_KEY']
    } catch {
      return undefined
    }
  }
}

/** Parse a code review response into structured data. */
function parseCodeReview(text: string): CodeReviewResult {
  const issues: CodeIssue[] = []
  const lines = text.split('\n')

  for (const line of lines) {
    const errorMatch = line.match(/(?:error|bug|critical)[\s:]+(?:line\s*(\d+)[\s:]+)?(.+)/i)
    if (errorMatch) { issues.push({ severity: 'error', line: errorMatch[1] ? parseInt(errorMatch[1]) : undefined, message: errorMatch[2]!.trim() }); continue }

    const warnMatch = line.match(/(?:warning|warn|perf|performance)[\s:]+(?:line\s*(\d+)[\s:]+)?(.+)/i)
    if (warnMatch) { issues.push({ severity: 'warning', line: warnMatch[1] ? parseInt(warnMatch[1]) : undefined, message: warnMatch[2]!.trim() }); continue }

    const infoMatch = line.match(/(?:info|style|suggestion|note)[\s:]+(?:line\s*(\d+)[\s:]+)?(.+)/i)
    if (infoMatch) { issues.push({ severity: 'info', line: infoMatch[1] ? parseInt(infoMatch[1]) : undefined, message: infoMatch[2]!.trim() }); continue }
  }

  const scoreMatch = text.match(/(?:score|rating)[\s:]*(\d+)/i)
  let score: number
  if (scoreMatch) {
    score = Math.min(100, Math.max(0, parseInt(scoreMatch[1]!)))
  } else {
    const hasErrors = issues.some(i => i.severity === 'error')
    score = hasErrors ? 50 : 80
  }

  const summaryMatch = text.match(/(?:summary|overall)[\s:]+(.+?)(?:\n|$)/i)
  const summary = summaryMatch?.[1]?.trim() ?? `Found ${issues.length} issue(s). Score: ${score}/100`

  const improvedMatch = text.match(/```(?:\w+)?\n([\s\S]*?)```/)
  const improvedCode = improvedMatch?.[1]?.trim()

  return { issues, score, summary, improvedCode }
}

// ╔═══════════════════════════════════════════════════════════════════════════════╗
// ║                                                                             ║
// ║  §8  ADVANCED CHAT — Main class tying it all together                       ║
// ║                                                                             ║
// ║  WHY THIS WAS MADE:                                                         ║
// ║  This is the ONE class that combines EVERYTHING into a single AI:           ║
// ║    • Chat management (messages, branches, pins, tags)                       ║
// ║    • AI intelligence (connected to Claude via AI Brain)                      ║
// ║    • Code writing (generate, review, fix code in 24 languages)              ║
// ║    • Image analysis (describe and understand photos)                        ║
// ║    • Smart context window (manages what fits in the LLM)                    ║
// ║    • Conversation search (find any message instantly)                        ║
// ║    • Analytics (token usage, cost, tools, code & image stats)               ║
// ║    • Export (Markdown, JSON, plain text)                                     ║
// ║    • Persistence (save and restore complete sessions)                        ║
// ║                                                                             ║
// ║  This single class IS the advanced AI.                                      ║
// ║                                                                             ║
// ╚═══════════════════════════════════════════════════════════════════════════════╝

function generateId(): string {
  if (typeof globalThis !== 'undefined' && 'crypto' in globalThis) {
    const c = globalThis.crypto as { randomUUID?: () => string }
    if (typeof c.randomUUID === 'function') return c.randomUUID()
  }
  const hex = Array.from({ length: 32 }, () => Math.floor(Math.random() * 16).toString(16)).join('')
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`
}

function estimateMessageTokens(msg: ChatMessage): number {
  if (msg.tokenUsage) return msg.tokenUsage.inputTokens + msg.tokenUsage.outputTokens
  const len = msg.content.reduce((s, b) => s + (b.text?.length ?? 0) + (b.toolResult?.length ?? 0) + (b.toolInput ? JSON.stringify(b.toolInput).length : 0), 0)
  return Math.ceil(len / 4)
}

const DEFAULT_CTX: ContextWindowConfig = { maxTokens: 200_000, reserveForResponse: 8_000, overflowStrategy: 'truncate_oldest', protectedPriorities: ['critical', 'high'] }

/**
 * 🤖 AdvancedChat — The complete AI system in one class.
 *
 * Capabilities:
 *  - **Chat**: Intelligent conversation powered by Claude
 *  - **Code**: Write, review, and fix code in 24+ languages
 *  - **Vision**: Analyze and describe images/photos
 *  - **Branch**: Fork conversations to explore alternatives
 *  - **Pin & Tag**: Bookmark important messages
 *  - **Search**: Fuzzy, exact, and regex search with scoring
 *  - **Analytics**: Token, cost, tool, code, and image stats
 *  - **Export**: Markdown, JSON, plain text
 *  - **Context**: Smart window management for LLM limits
 *  - **Persist**: Save and restore complete sessions
 */
export class AdvancedChat {
  private conversation: Conversation
  private contextConfig: ContextWindowConfig
  private messagePriorities = new Map<ChatMessageId, MessagePriority>()
  public readonly brain: BrainInterface

  constructor(options?: {
    title?: string
    contextConfig?: Partial<ContextWindowConfig>
    metadata?: Partial<ConversationMetadata>
    apiKey?: string
    model?: string
    /** Pass a custom brain (e.g. LocalBrain) to use instead of the default AiBrain. */
    brain?: BrainInterface
  }) {
    const now = new Date().toISOString()
    this.conversation = {
      id: generateId(),
      title: options?.title ?? 'New Conversation',
      branches: [{ id: 'main', label: 'Main', createdAt: now }],
      activeBranchId: 'main',
      messages: [],
      createdAt: now,
      updatedAt: now,
      totalTokenUsage: emptyUsage(),
      metadata: { modelsUsed: [], totalToolCalls: 0, estimatedCostUsd: 0, ...options?.metadata },
    }
    this.contextConfig = { ...DEFAULT_CTX, ...options?.contextConfig }
    this.brain = options?.brain ?? new AiBrain({ apiKey: options?.apiKey, model: options?.model })
  }

  // ── Conversation State ──

  getConversation(): Readonly<Conversation> { return this.conversation }
  getTitle(): string { return this.conversation.title }
  setTitle(title: string): void { this.conversation.title = title; this.touch() }
  getActiveBranchId(): BranchId { return this.conversation.activeBranchId }

  // ── Message Management ──

  addMessage(p: { role: ChatRole; content: ContentBlock[]; model?: string; tokenUsage?: TokenUsage; apiDurationMs?: number; tags?: string[]; priority?: MessagePriority }): ChatMessage {
    const msg: ChatMessage = { id: generateId(), role: p.role, content: p.content, timestamp: new Date().toISOString(), branchId: this.conversation.activeBranchId, pinned: false, tags: p.tags ?? [], tokenUsage: p.tokenUsage, model: p.model, apiDurationMs: p.apiDurationMs }
    this.conversation.messages.push(msg)
    if (msg.tokenUsage) this.conversation.totalTokenUsage = addUsage(this.conversation.totalTokenUsage, msg.tokenUsage)
    if (msg.model && !this.conversation.metadata.modelsUsed.includes(msg.model)) this.conversation.metadata.modelsUsed.push(msg.model)
    for (const b of msg.content) if (b.type === 'tool_use') this.conversation.metadata.totalToolCalls++
    if (p.priority) this.messagePriorities.set(msg.id, p.priority)
    this.touch()
    return msg
  }

  addUserMessage(text: string, tags?: string[]): ChatMessage {
    return this.addMessage({ role: 'user', content: [{ type: 'text', text }], tags, priority: 'high' })
  }

  addAssistantMessage(text: string, opts?: { model?: string; tokenUsage?: TokenUsage; apiDurationMs?: number }): ChatMessage {
    return this.addMessage({ role: 'assistant', content: [{ type: 'text', text }], model: opts?.model, tokenUsage: opts?.tokenUsage, apiDurationMs: opts?.apiDurationMs, priority: 'medium' })
  }

  getMessages(branchId?: BranchId): ChatMessage[] {
    const bid = branchId ?? this.conversation.activeBranchId
    return this.conversation.messages.filter(m => m.branchId === bid).sort((a, b) => a.timestamp.localeCompare(b.timestamp))
  }

  getMessage(id: ChatMessageId): ChatMessage | undefined { return this.conversation.messages.find(m => m.id === id) }
  getMessageCount(): number { return this.conversation.messages.length }

  // ── 🤖 AI Chat (powered by Claude) ──

  /** Send a message to the AI and get an intelligent response. */
  async sendMessage(text: string, tags?: string[]): Promise<ChatMessage> {
    this.addUserMessage(text, tags)
    const response = await this.brain.chat(text)
    return this.addAssistantMessage(response.text, {
      model: this.brain.getModel(),
      tokenUsage: response.usage,
      apiDurationMs: response.durationMs,
    })
  }

  // ── 💻 Code Writing ──

  /** Ask the AI to write code. Returns the code as a message in the conversation. */
  async writeCode(request: CodeRequest): Promise<{ message: ChatMessage; result: CodeResult }> {
    this.addUserMessage(`Write ${request.language} code: ${request.description}`, ['code', request.language])
    const result = await this.brain.writeCode(request)
    const msg = this.addMessage({
      role: 'assistant',
      content: [
        { type: 'code', text: result.code, language: result.language },
        { type: 'text', text: result.explanation },
      ],
      model: this.brain.getModel(),
      tags: ['code', request.language],
      priority: 'high',
    })
    return { message: msg, result }
  }

  /** Ask the AI to review code. */
  async reviewCode(request: CodeReviewRequest): Promise<{ message: ChatMessage; result: CodeReviewResult }> {
    this.addUserMessage(`Review this ${request.language} code`, ['code-review', request.language])
    const result = await this.brain.reviewCode(request)
    const issueText = result.issues.map(i => `[${i.severity.toUpperCase()}]${i.line ? ` Line ${i.line}:` : ''} ${i.message}`).join('\n')
    const msg = this.addAssistantMessage(
      `## Code Review (Score: ${result.score}/100)\n\n${result.summary}\n\n### Issues:\n${issueText || 'No issues found! ✅'}${result.improvedCode ? `\n\n### Improved Code:\n\`\`\`${request.language}\n${result.improvedCode}\n\`\`\`` : ''}`,
      { model: this.brain.getModel() },
    )
    return { message: msg, result }
  }

  // ── 🖼 Image Analysis ──

  /** Analyze an image and add the result to the conversation. */
  async analyzeImage(request: ImageAnalysisRequest): Promise<{ message: ChatMessage; result: ImageAnalysisResult }> {
    this.addMessage({
      role: 'user',
      content: [createImageBlock(request.imageData, request.mediaType), { type: 'text', text: request.question ?? 'Analyze this image' }],
      tags: ['image'],
      priority: 'high',
    })
    const result = await this.brain.analyzeImage(request)
    const msg = this.addAssistantMessage(
      `## 🖼 Image Analysis\n\n${result.description}\n\n**Objects:** ${result.objects.join(', ') || 'none detected'}\n**Colors:** ${result.colors.join(', ') || 'none detected'}\n${result.text ? `**Text:** "${result.text}"` : ''}\n**Mood:** ${result.sentiment ?? 'neutral'}\n**Tags:** ${result.tags.join(', ')}`,
      { model: this.brain.getModel() },
    )
    return { message: msg, result }
  }

  // ── 📌 Pinning & Tagging ──

  togglePin(messageId: ChatMessageId): boolean {
    const msg = this.conversation.messages.find(m => m.id === messageId)
    if (!msg) return false
    msg.pinned = !msg.pinned; this.touch()
    return msg.pinned
  }

  addTag(messageId: ChatMessageId, tag: string): boolean {
    const msg = this.conversation.messages.find(m => m.id === messageId)
    if (!msg) return false
    if (!msg.tags.includes(tag)) { msg.tags.push(tag); this.touch() }
    return true
  }

  removeTag(messageId: ChatMessageId, tag: string): boolean {
    const msg = this.conversation.messages.find(m => m.id === messageId)
    if (!msg) return false
    const idx = msg.tags.indexOf(tag)
    if (idx >= 0) { msg.tags.splice(idx, 1); this.touch(); return true }
    return false
  }

  getPinnedMessages(branchId?: BranchId): ChatMessage[] {
    return getPinnedMessages(this.conversation.messages, branchId ?? this.conversation.activeBranchId)
  }

  // ── 🌿 Branching ──

  forkBranch(forkAtMessageId: ChatMessageId, label?: string): BranchId {
    const src = this.conversation.messages.find(m => m.id === forkAtMessageId)
    if (!src) throw new Error(`Message ${forkAtMessageId} not found`)
    const newId = generateId()
    const branch: Branch = { id: newId, label: label ?? `Branch ${this.conversation.branches.length + 1}`, parentBranchId: src.branchId, forkPointMessageId: forkAtMessageId, createdAt: new Date().toISOString() }
    for (const msg of this.getMessages(src.branchId)) {
      this.conversation.messages.push({ ...msg, id: generateId(), branchId: newId, parentMessageId: msg.id })
      if (msg.id === forkAtMessageId) break
    }
    this.conversation.branches.push(branch)
    this.conversation.activeBranchId = newId
    this.touch()
    return newId
  }

  switchBranch(branchId: BranchId): void {
    if (!this.conversation.branches.find(b => b.id === branchId)) throw new Error(`Branch ${branchId} not found`)
    this.conversation.activeBranchId = branchId; this.touch()
  }

  getBranches(): ReadonlyArray<Branch> { return this.conversation.branches }

  // ── 🧠 Smart Context Window ──

  buildContextWindow(branchId?: BranchId): ContextWindowResult {
    const msgs = this.getMessages(branchId)
    const budget = this.contextConfig.maxTokens - this.contextConfig.reserveForResponse
    const items = msgs.map(m => ({ message: m, priority: this.messagePriorities.get(m.id) ?? 'medium' as MessagePriority, tokens: estimateMessageTokens(m) }))
    let total = items.reduce((s, p) => s + p.tokens, 0)
    if (total <= budget) return { messages: msgs, totalTokens: total, droppedCount: 0, wasTruncated: false }

    const kept: typeof items = []
    let dropped = 0
    if (this.contextConfig.overflowStrategy === 'drop_low_priority') {
      const order: MessagePriority[] = ['critical', 'high', 'medium', 'low']
      const sorted = [...items].sort((a, b) => order.indexOf(a.priority) - order.indexOf(b.priority))
      let rem = budget; const ids = new Set<string>()
      for (const e of sorted) { if (rem >= e.tokens) { ids.add(e.message.id); rem -= e.tokens } else dropped++ }
      for (const e of items) if (ids.has(e.message.id)) kept.push(e)
    } else {
      const rev = [...items].reverse(); let rem = budget
      for (const e of rev) {
        if (rem >= e.tokens || this.contextConfig.protectedPriorities.includes(e.priority)) { kept.unshift(e); rem -= e.tokens } else dropped++
      }
    }
    total = kept.reduce((s, p) => s + p.tokens, 0)
    return { messages: kept.map(k => k.message), totalTokens: total, droppedCount: dropped, wasTruncated: dropped > 0 }
  }

  setContextConfig(config: Partial<ContextWindowConfig>): void { this.contextConfig = { ...this.contextConfig, ...config } }
  getContextConfig(): Readonly<ContextWindowConfig> { return this.contextConfig }

  // ── 🔍 Search ──

  search(options: ChatSearchOptions): ChatSearchResult[] { return searchMessages(this.conversation.messages, options) }
  searchByTool(toolName: string, limit?: number): ChatSearchResult[] { return searchByTool(this.conversation.messages, toolName, limit) }

  // ── 📊 Analytics ──

  getAnalytics(branchId?: BranchId): ConversationAnalytics {
    return computeAnalytics(branchId ? this.getMessages(branchId) : this.conversation.messages)
  }
  getTopTools(n?: number) { return getTopTools(this.conversation.messages, n) }
  getTurnBreakdown(branchId?: BranchId) { return getTurnBreakdown(this.getMessages(branchId)) }

  // ── 📤 Export ──

  export(options: ExportOptions): string { return exportConversation(this.conversation.messages, options) }

  exportMarkdown(): string {
    return this.export({ format: 'markdown', branchId: this.conversation.activeBranchId, includeToolBlocks: true, includeTokenUsage: true, includeAnalytics: true, includeCode: true })
  }

  exportJSON(): string {
    return this.export({ format: 'json', branchId: this.conversation.activeBranchId, includeSystemMessages: true, includeToolBlocks: true, includeTokenUsage: true, includeAnalytics: true, includeCode: true })
  }

  // ── 💾 Persistence ──

  serialize(): string {
    return JSON.stringify({ conversation: this.conversation, contextConfig: this.contextConfig, messagePriorities: Object.fromEntries(this.messagePriorities), model: this.brain.getModel() })
  }

  static deserialize(json: string, apiKey?: string): AdvancedChat {
    const d = JSON.parse(json) as { conversation: Conversation; contextConfig: ContextWindowConfig; messagePriorities: Record<string, MessagePriority>; model?: string }
    const chat = new AdvancedChat({ apiKey, model: d.model })
    chat.conversation = d.conversation
    chat.contextConfig = d.contextConfig
    chat.messagePriorities = new Map(Object.entries(d.messagePriorities))
    return chat
  }

  // ── Internal ──

  private touch(): void { this.conversation.updatedAt = new Date().toISOString() }
}
