/**
 * ╔═══════════════════════════════════════════════════════════════════════════════╗
 * ║                                                                             ║
 * ║   🧠 Shared Types & Utilities for AI Modules                                ║
 * ║                                                                             ║
 * ║   Extracted from AiChat.ts to enable offline-only modules                   ║
 * ║   (LocalBrain, DevBrain) without cloud API dependencies.                    ║
 * ║                                                                             ║
 * ╚═══════════════════════════════════════════════════════════════════════════════╝
 */

// ── Message Primitives ───────────────────────────────────────────────────────

export type ChatMessageId = string
export type BranchId = string
export type ChatRole = 'user' | 'assistant' | 'system' | 'tool'
export type ContentBlockType = 'text' | 'tool_use' | 'tool_result' | 'image' | 'code'

/** A single content block inside a message. */
export interface ContentBlock {
  type: ContentBlockType
  text?: string
  toolName?: string
  toolInput?: Record<string, unknown>
  toolResult?: string
  toolUseId?: string
  /** Programming language (when type is "code"). */
  language?: string
  /** Base64-encoded image data (when type is "image"). */
  imageData?: string
  /** Image media type, e.g. "image/png" (when type is "image"). */
  mediaType?: string
  /** Image description generated by vision AI (when type is "image"). */
  imageDescription?: string
}

/** A single chat message with full metadata. */
export interface ChatMessage {
  id: ChatMessageId
  role: ChatRole
  content: ContentBlock[]
  timestamp: string
  branchId: BranchId
  parentMessageId?: ChatMessageId
  pinned: boolean
  tags: string[]
  tokenUsage?: TokenUsage
  model?: string
  apiDurationMs?: number
}

export interface TokenUsage {
  inputTokens: number
  outputTokens: number
  cacheReadTokens?: number
  cacheCreationTokens?: number
}

// ── Conversation & Branching ─────────────────────────────────────────────────

export interface Branch {
  id: BranchId
  label: string
  parentBranchId?: BranchId
  forkPointMessageId?: ChatMessageId
  createdAt: string
}

export interface Conversation {
  id: string
  title: string
  messages: ChatMessage[]
  branches: Branch[]
  activeBranchId: BranchId
  metadata: ConversationMetadata
}

export interface ConversationMetadata {
  createdAt: string
  updatedAt: string
  messageCount: number
  totalTokens: number
  totalCost: number
  tags: string[]
  model: string
}

// ── Search Types ─────────────────────────────────────────────────────────────

export type SearchMode = 'fuzzy' | 'exact' | 'regex' | 'semantic'

export interface ChatSearchOptions {
  query: string
  mode?: SearchMode
  roles?: ChatRole[]
  dateRange?: { start: string; end: string }
  branchId?: BranchId
  tags?: string[]
  limit?: number
}

export interface ChatSearchResult {
  message: ChatMessage
  score: number
  matchPositions: Array<{ start: number; end: number }>
  highlights: SearchHighlight[]
}

export interface SearchHighlight {
  text: string
  isMatch: boolean
}

// ── Analytics Types ──────────────────────────────────────────────────────────

export interface ConversationAnalytics {
  totalMessages: number
  userMessages: number
  assistantMessages: number
  totalTokens: number
  totalCost: number
  averageResponseTime: number
  modelUsage: ModelUsageBreakdown[]
  topTools: Array<{ tool: string; count: number }>
  codeStats: CodeStats
  imageStats: ImageStats
}

export interface ModelUsageBreakdown {
  model: string
  messages: number
  tokens: number
  cost: number
}

export interface CodeStats {
  totalBlocks: number
  languages: Record<string, number>
  totalLines: number
}

export interface ImageStats {
  totalImages: number
  analyzedCount: number
}

// ── Export Types ──────────────────────────────────────────────────────────────

export type ExportFormat = 'markdown' | 'json' | 'text'

export interface ExportOptions {
  format: ExportFormat
  includeMetadata?: boolean
  includeTokenUsage?: boolean
  branchId?: BranchId
}

// ── Context Window Types ─────────────────────────────────────────────────────

export type MessagePriority = 'critical' | 'high' | 'medium' | 'low'

export interface ContextWindowConfig {
  maxTokens: number
  reserveForResponse: number
  overflowStrategy: 'truncate_oldest' | 'summarize' | 'drop_low_priority'
  protectedPriorities: MessagePriority[]
}

export interface ContextWindowResult {
  messages: ChatMessage[]
  totalTokens: number
  droppedCount: number
  wasTruncated: boolean
}

// ── Code Writer Types ────────────────────────────────────────────────────────

/** All languages the AI can write code in. */
export type ProgrammingLanguage =
  | 'typescript'
  | 'javascript'
  | 'python'
  | 'rust'
  | 'go'
  | 'java'
  | 'c'
  | 'cpp'
  | 'csharp'
  | 'swift'
  | 'kotlin'
  | 'ruby'
  | 'php'
  | 'html'
  | 'css'
  | 'sql'
  | 'bash'
  | 'powershell'
  | 'r'
  | 'dart'
  | 'scala'
  | 'lua'
  | 'haskell'
  | 'elixir'

/** Request to generate code. */
export interface CodeRequest {
  description: string
  language: ProgrammingLanguage
  context?: string
  style?: 'concise' | 'detailed' | 'production'
}

/** Result of code generation. */
export interface CodeResult {
  code: string
  language: ProgrammingLanguage
  explanation: string
  linesOfCode: number
  complexity: 'simple' | 'moderate' | 'complex'
}

/** Request to review code. */
export interface CodeReviewRequest {
  code: string
  language: ProgrammingLanguage
  focus?: ('bugs' | 'performance' | 'security' | 'style' | 'all')[]
}

/** Result of code review. */
export interface CodeReviewResult {
  issues: CodeIssue[]
  score: number
  summary: string
  improvedCode?: string
}

export interface CodeIssue {
  severity: 'error' | 'warning' | 'info'
  line?: number
  message: string
  suggestion?: string
}

// ── Image Analysis Types ─────────────────────────────────────────────────────

/** Request to analyze an image. */
export interface ImageAnalysisRequest {
  imageData: string
  mediaType: string
  question?: string
}

/** Result of image analysis. */
export interface ImageAnalysisResult {
  description: string
  objects: string[]
  colors: string[]
  text?: string
  sentiment?: string
  tags: string[]
}

// ── AI Brain Types ───────────────────────────────────────────────────────────

/** Configuration for the AI Brain. */
export interface AiBrainConfig {
  apiKey?: string
  model: string
  maxTokens: number
  temperature: number
  systemPrompt: string
}

/** A message in the format APIs expect. */
export interface ApiMessage {
  role: 'user' | 'assistant'
  content: string | ApiContentBlock[]
}

/**
 * Common interface that any brain (LocalBrain, DevBrain, or custom) must implement.
 * This allows code to work with any brain implementation.
 */
export interface BrainInterface {
  chat(userMessage: string): Promise<{ text: string; usage: TokenUsage; durationMs: number }>
  writeCode(request: CodeRequest): Promise<CodeResult>
  reviewCode(request: CodeReviewRequest): Promise<CodeReviewResult>
  analyzeImage(request: ImageAnalysisRequest): Promise<ImageAnalysisResult>
  analyzeDocument(request: DocumentAnalysisInput): Promise<DocumentAnalysisOutput>
  getModel(): string
  setModel(model: string): void
  clearHistory(): void
}

/** Lightweight document analysis input (full types in DocumentAnalyzer). */
export interface DocumentAnalysisInput {
  content: string
  fileName?: string
  mimeType?: string
  question?: string
}

/** Lightweight document analysis output (compatible with DocumentAnalysisResult). */
export interface DocumentAnalysisOutput {
  description: string
  wordCount: number
  estimatedPages: number
  keywords: readonly string[]
  readabilityLevel: string
  documentType: string
  sentiment: string
  sections: readonly { title: string; wordCount: number }[]
  answer: string | null
  confidence: number
  processingMs: number
}

export interface ApiContentBlock {
  type: 'text' | 'image'
  text?: string
  source?: {
    type: 'base64'
    media_type: string
    data: string
  }
}

// ═══════════════════════════════════════════════════════════════════════════════
// CODE WRITER UTILITIES — Offline code analysis functions
// ═══════════════════════════════════════════════════════════════════════════════

/** File extensions and comment syntax per language. */
const LANG_INFO: Record<string, { ext: string; comment: string; block?: [string, string] }> = {
  typescript: { ext: '.ts', comment: '//', block: ['/*', '*/'] },
  javascript: { ext: '.js', comment: '//', block: ['/*', '*/'] },
  python: { ext: '.py', comment: '#', block: ['"""', '"""'] },
  rust: { ext: '.rs', comment: '//', block: ['/*', '*/'] },
  go: { ext: '.go', comment: '//', block: ['/*', '*/'] },
  java: { ext: '.java', comment: '//', block: ['/*', '*/'] },
  c: { ext: '.c', comment: '//', block: ['/*', '*/'] },
  cpp: { ext: '.cpp', comment: '//', block: ['/*', '*/'] },
  csharp: { ext: '.cs', comment: '//', block: ['/*', '*/'] },
  swift: { ext: '.swift', comment: '//', block: ['/*', '*/'] },
  kotlin: { ext: '.kt', comment: '//', block: ['/*', '*/'] },
  ruby: { ext: '.rb', comment: '#', block: ['=begin', '=end'] },
  php: { ext: '.php', comment: '//', block: ['/*', '*/'] },
  html: { ext: '.html', comment: '', block: ['<!--', '-->'] },
  css: { ext: '.css', comment: '', block: ['/*', '*/'] },
  sql: { ext: '.sql', comment: '--' },
  bash: { ext: '.sh', comment: '#' },
  powershell: { ext: '.ps1', comment: '#', block: ['<#', '#>'] },
  r: { ext: '.R', comment: '#' },
  dart: { ext: '.dart', comment: '//', block: ['/*', '*/'] },
  scala: { ext: '.scala', comment: '//', block: ['/*', '*/'] },
  lua: { ext: '.lua', comment: '--', block: ['--[[', ']]'] },
  haskell: { ext: '.hs', comment: '--', block: ['{-', '-}'] },
  elixir: { ext: '.ex', comment: '#' },
}

/** Starter templates for common code patterns per language. */
const CODE_TEMPLATES: Record<string, Record<string, string>> = {
  typescript: {
    function: 'export function {{name}}({{params}}): {{returnType}} {\n  {{body}}\n}',
    class: 'export class {{name}} {\n  constructor({{params}}) {\n    {{body}}\n  }\n}',
    interface: 'export interface {{name}} {\n  {{body}}\n}',
    test: 'describe("{{name}}", () => {\n  it("should {{description}}", () => {\n    {{body}}\n  })\n})',
    api: 'export async function {{name}}(req: Request): Promise<Response> {\n  {{body}}\n  return new Response(JSON.stringify({ ok: true }), { status: 200 })\n}',
  },
  python: {
    function: 'def {{name}}({{params}}){{returnType}}:\n    """{{description}}"""\n    {{body}}',
    class:
      'class {{name}}:\n    """{{description}}"""\n\n    def __init__(self, {{params}}):\n        {{body}}',
    test: 'def test_{{name}}():\n    """{{description}}"""\n    {{body}}\n    assert result == expected',
    api: '@app.route("/{{name}}", methods=["GET"])\ndef {{name}}():\n    """{{description}}"""\n    {{body}}\n    return jsonify({"ok": True})',
    dataclass:
      'from dataclasses import dataclass\n\n@dataclass\nclass {{name}}:\n    """{{description}}"""\n    {{body}}',
  },
  rust: {
    function: 'pub fn {{name}}({{params}}) -> {{returnType}} {\n    {{body}}\n}',
    struct:
      'pub struct {{name}} {\n    {{body}}\n}\n\nimpl {{name}} {\n    pub fn new({{params}}) -> Self {\n        Self { {{body}} }\n    }\n}',
    test: '#[cfg(test)]\nmod tests {\n    use super::*;\n\n    #[test]\n    fn test_{{name}}() {\n        {{body}}\n    }\n}',
    enum_: 'pub enum {{name}} {\n    {{body}}\n}',
  },
  go: {
    function: 'func {{name}}({{params}}) {{returnType}} {\n\t{{body}}\n}',
    struct:
      'type {{name}} struct {\n\t{{body}}\n}\n\nfunc New{{name}}({{params}}) *{{name}} {\n\treturn &{{name}}{{{body}}}\n}',
    test: 'func Test{{name}}(t *testing.T) {\n\t{{body}}\n}',
    handler:
      'func {{name}}Handler(w http.ResponseWriter, r *http.Request) {\n\t{{body}}\n\tjson.NewEncoder(w).Encode(map[string]bool{"ok": true})\n}',
  },
  java: {
    class:
      'public class {{name}} {\n    {{body}}\n\n    public {{name}}({{params}}) {\n        {{body}}\n    }\n}',
    method: 'public {{returnType}} {{name}}({{params}}) {\n    {{body}}\n}',
    test: '@Test\npublic void test{{name}}() {\n    {{body}}\n    assertEquals(expected, result);\n}',
    interface: 'public interface {{name}} {\n    {{body}}\n}',
  },
}

const SUPPORTED_IMAGE_TYPES = ['image/png', 'image/jpeg', 'image/gif', 'image/webp'] as const

/** Detect the programming language from source code. */
export function detectLanguage(code: string): ProgrammingLanguage {
  const indicators: Array<[ProgrammingLanguage, RegExp[]]> = [
    [
      'typescript',
      [/:\s*(string|number|boolean|void|any)\b/, /interface\s+\w+/, /import\s+type\s/],
    ],
    ['python', [/def\s+\w+\s*\(/, /import\s+\w+/, /if\s+__name__\s*==\s*['"]__main__['"]/]],
    ['rust', [/fn\s+\w+\s*\(/, /let\s+mut\s/, /impl\s+\w+/, /pub\s+fn\s/]],
    ['go', [/func\s+\w+\s*\(/, /package\s+\w+/, /import\s+\(/, /:=\s/]],
    ['java', [/public\s+class\s/, /System\.out\.print/, /public\s+static\s+void\s+main/]],
    ['csharp', [/using\s+System/, /namespace\s+\w+/, /public\s+class\s/, /Console\.Write/]],
    ['swift', [/func\s+\w+\s*\(.*\)\s*->/, /let\s+\w+\s*:\s*\w+/, /import\s+Foundation/]],
    ['kotlin', [/fun\s+\w+\s*\(/, /val\s+\w+\s*[:=]/, /package\s+\w+\.\w+/]],
    ['ruby', [/def\s+\w+/, /end\s*$/, /require\s+['"]/, /class\s+\w+\s*<?\s/]],
    ['php', [/<\?php/, /\$\w+\s*=/, /function\s+\w+\s*\(/]],
    ['html', [/<html/, /<div/, /<body/, /<!DOCTYPE/i]],
    ['css', [/[.#]\w+\s*\{/, /@media\s/, /:\s*(flex|grid|block|none)\s*;/]],
    ['sql', [/SELECT\s+/i, /CREATE\s+TABLE/i, /INSERT\s+INTO/i]],
    ['bash', [/^#!/, /echo\s+/, /if\s+\[\[?\s/]],
    ['lua', [/local\s+\w+\s*=/, /function\s+\w+\s*\(/, /end\s*$/]],
    ['haskell', [/module\s+\w+/, /::\s*/, /import\s+qualified/]],
    ['elixir', [/defmodule\s/, /def\s+\w+\s*do/, /\|>\s/]],
    ['dart', [/void\s+main\s*\(/, /Widget\s+build/, /import\s+'package:/]],
    ['scala', [/object\s+\w+/, /def\s+\w+\s*\(/, /val\s+\w+\s*:\s/]],
    ['javascript', [/const\s+\w+\s*=/, /function\s+\w+\s*\(/, /=>\s*\{/, /require\s*\(/]],
  ]
  for (const [lang, patterns] of indicators) {
    const matches = patterns.filter(p => p.test(code)).length
    if (matches >= 2) return lang
  }
  return 'javascript'
}

/** Count lines of code (excluding blank lines and comments). */
export function countLinesOfCode(
  code: string,
  language: ProgrammingLanguage,
): { total: number; code: number; blank: number; comment: number } {
  const lines = code.split('\n')
  const info = LANG_INFO[language]
  let codeLines = 0,
    blank = 0,
    comment = 0,
    inBlock = false
  const blockStart = info?.block?.[0],
    blockEnd = info?.block?.[1]

  for (const line of lines) {
    const trimmed = line.trim()
    if (!trimmed) {
      blank++
      continue
    }
    if (inBlock) {
      comment++
      if (blockEnd && trimmed.includes(blockEnd)) inBlock = false
      continue
    }
    if (blockStart && trimmed.startsWith(blockStart)) {
      comment++
      if (blockEnd && !trimmed.includes(blockEnd)) inBlock = true
      continue
    }
    if (info?.comment && trimmed.startsWith(info.comment)) {
      comment++
      continue
    }
    codeLines++
  }
  return { total: lines.length, code: codeLines, blank, comment }
}

/** Estimate complexity of code. */
export function estimateComplexity(code: string): 'simple' | 'moderate' | 'complex' {
  const lines = code.split('\n').length
  const nesting =
    Math.max(
      ...code
        .split('\n')
        .map(l => l.search(/\S/))
        .filter(n => n >= 0),
    ) / 2
  const branches = (code.match(/\b(if|else|switch|case|for|while|try|catch)\b/g) || []).length
  const score = lines * 0.3 + nesting * 2 + branches * 1.5
  if (score < 15) return 'simple'
  if (score < 50) return 'moderate'
  return 'complex'
}

/** Get a code template for a specific language and pattern. */
export function getCodeTemplate(
  language: ProgrammingLanguage,
  pattern: string,
): string | undefined {
  return CODE_TEMPLATES[language]?.[pattern]
}

/** Get language info (extension, comment syntax). */
export function getLanguageInfo(language: ProgrammingLanguage) {
  return LANG_INFO[language] ?? { ext: '.txt', comment: '//' }
}

/** Format code with consistent indentation. */
export function formatCode(code: string, indentSize = 2): string {
  const indent = ' '.repeat(indentSize)
  let level = 0
  return code
    .split('\n')
    .map(line => {
      const trimmed = line.trim()
      if (!trimmed) return ''
      if (trimmed.startsWith('}') || trimmed.startsWith(')') || trimmed.startsWith(']'))
        level = Math.max(0, level - 1)
      const result = indent.repeat(level) + trimmed
      if (trimmed.endsWith('{') || trimmed.endsWith('(') || trimmed.endsWith('[')) level++
      return result
    })
    .join('\n')
}

/** Check if a media type is supported for image analysis. */
export function isSupportedImageType(mediaType: string): boolean {
  return (SUPPORTED_IMAGE_TYPES as readonly string[]).includes(mediaType)
}

/** Validate base64 image data. Returns true if the data looks like valid base64. */
export function validateImageData(data: string): boolean {
  if (!data || data.length === 0) return false
  if (data.length > 20_000_000) return false
  return /^[A-Za-z0-9+/]+=*$/.test(data.replace(/\s/g, ''))
}

/** Estimate image file size from base64 data (in bytes). */
export function estimateImageSize(base64Data: string): number {
  const cleanData = base64Data.replace(/\s/g, '')
  return Math.floor(cleanData.length * 0.75)
}

/** Build a vision content block for an image. */
export function buildImageContentBlock(
  imageData: string,
  mediaType: string,
  question?: string,
): ApiContentBlock[] {
  const blocks: ApiContentBlock[] = [
    { type: 'image', source: { type: 'base64', media_type: mediaType, data: imageData } },
  ]
  if (question) {
    blocks.push({ type: 'text', text: question })
  } else {
    blocks.push({
      type: 'text',
      text: 'Describe this image in detail. What do you see? Include objects, colors, text, people, actions, and any other notable elements.',
    })
  }
  return blocks
}

/** Create a ChatMessage content block for an analyzed image. */
export function createImageBlock(
  imageData: string,
  mediaType: string,
  description?: string,
): ContentBlock {
  return {
    type: 'image',
    imageData,
    mediaType,
    imageDescription: description,
  }
}

/** Parse a text description into structured image analysis. */
export function parseImageAnalysis(description: string): ImageAnalysisResult {
  const colorPatterns =
    /\b(red|blue|green|yellow|orange|purple|pink|black|white|gray|grey|brown|cyan|magenta|gold|silver|beige|navy|teal|maroon|olive|coral|salmon|lavender|turquoise|indigo|violet)\b/gi
  const colors = [...new Set((description.match(colorPatterns) ?? []).map(c => c.toLowerCase()))]

  const objectPatterns =
    /\b(person|people|man|woman|child|dog|cat|car|tree|building|house|table|chair|phone|computer|book|flower|mountain|sky|sun|moon|water|road|door|window|wall|lamp|clock|cup|bottle|bag|hat|shirt|shoe|hand|face|eye|cloud|bird|fish|boat|airplane|train|bridge|park|garden|street|sign|light|shadow)\b/gi
  const objects = [...new Set((description.match(objectPatterns) ?? []).map(o => o.toLowerCase()))]

  const textMatch = description.match(
    /text\s+(?:that\s+)?(?:reads?|says?|shows?)\s*[:"]?\s*["']?([^"'\n.]+)/i,
  )
  const text = textMatch?.[1]?.trim()

  const sentimentWords = {
    positive:
      /\b(happy|beautiful|bright|cheerful|peaceful|stunning|elegant|vibrant|warm|inviting|cozy)\b/i,
    negative: /\b(dark|gloomy|sad|lonely|broken|damaged|dirty|ugly|scary|ominous|bleak)\b/i,
  }
  const posCount = (description.match(sentimentWords.positive) ?? []).length
  const negCount = (description.match(sentimentWords.negative) ?? []).length
  const sentiment = posCount > negCount ? 'positive' : negCount > posCount ? 'negative' : 'neutral'

  const tags = [...objects.slice(0, 5), ...colors.slice(0, 3)]
  if (text) tags.push('has-text')
  if (description.toLowerCase().includes('photo')) tags.push('photograph')
  if (description.toLowerCase().includes('screenshot')) tags.push('screenshot')
  if (description.toLowerCase().includes('diagram')) tags.push('diagram')
  if (description.toLowerCase().includes('chart') || description.toLowerCase().includes('graph'))
    tags.push('data-visualization')

  return { description, objects, colors, text, sentiment, tags }
}
